//
//  MightyMindersUI.swift
//  MightyMinders
//
//  Created by Justin Bane on 9/26/16.
//  Copyright (c) 2016 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class MightyMindersUI : NSObject {

    //// Cache

    private struct Cache {
        static let green: UIColor = UIColor(red: 0.180, green: 0.800, blue: 0.443, alpha: 1.000)
        static let darkGreen: UIColor = MightyMindersUI.green.colorWithBrightness(0.6)
        static let white: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        static let lightGrey: UIColor = MightyMindersUI.white.colorWithBrightness(0.9)
        static let grey: UIColor = MightyMindersUI.white.colorWithBrightness(0.5)
        static let baseShadow: NSShadow = NSShadow(color: UIColor.darkGrayColor(), offset: CGSize(width: 3.1, height: 3.1), blurRadius: 5)
        static let lowShadow: NSShadow = NSShadow(color: UIColor.grayColor(), offset: CGSize(width: 2.1, height: 3.1), blurRadius: 4)
    }

    //// Colors

    public class var green: UIColor { return Cache.green }
    public class var darkGreen: UIColor { return Cache.darkGreen }
    public class var white: UIColor { return Cache.white }
    public class var lightGrey: UIColor { return Cache.lightGrey }
    public class var grey: UIColor { return Cache.grey }

    //// Shadows

    public class var baseShadow: NSShadow { return Cache.baseShadow }
    public class var lowShadow: NSShadow { return Cache.lowShadow }

    //// Drawing Methods

    public class func drawAddButton(frame frame: CGRect = CGRect(x: 0, y: 0, width: 106, height: 106), pressed: Bool = false) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Subframes
        let group: CGRect = CGRect(x: frame.minX + 17.5, y: frame.minY + 16.5, width: frame.width - 46, height: frame.height - 46)


        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRect(x: frame.minX + floor((frame.width - 13) * 0.03226 + 0.5), y: frame.minY + floor((frame.height - 13) * 0.03226 + 0.5), width: frame.width - 13 - floor((frame.width - 13) * 0.03226 + 0.5), height: frame.height - 13 - floor((frame.height - 13) * 0.03226 + 0.5)))
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, MightyMindersUI.lowShadow.shadowOffset, MightyMindersUI.lowShadow.shadowBlurRadius, (MightyMindersUI.lowShadow.shadowColor as! UIColor).CGColor)
        MightyMindersUI.green.setFill()
        ovalPath.fill()
        CGContextRestoreGState(context)

        MightyMindersUI.darkGreen.setStroke()
        ovalPath.lineWidth = 1
        ovalPath.stroke()


        if (pressed) {
            //// Oval  pressed Drawing
            let ovalPressedPath = UIBezierPath(ovalInRect: CGRect(x: frame.minX + 3, y: frame.minY + 3, width: frame.width - 16, height: frame.height - 16))
            MightyMindersUI.darkGreen.setFill()
            ovalPressedPath.fill()
            MightyMindersUI.darkGreen.setStroke()
            ovalPressedPath.lineWidth = 1
            ovalPressedPath.stroke()
        }


        //// Group
        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPoint(x: group.minX + 0.49998 * group.width, y: group.minY + 0.00000 * group.height))
        bezier3Path.addCurveToPoint(CGPoint(x: group.minX + 0.49998 * group.width, y: group.minY + 1.00000 * group.height), controlPoint1: CGPoint(x: group.minX + 0.51665 * group.width, y: group.minY + 1.00000 * group.height), controlPoint2: CGPoint(x: group.minX + 0.49998 * group.width, y: group.minY + 1.00000 * group.height))
        bezier3Path.moveToPoint(CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.53332 * group.height))
        bezier3Path.addCurveToPoint(CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 0.53332 * group.height), controlPoint1: CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 0.51665 * group.height), controlPoint2: CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 0.53332 * group.height))
        bezier3Path.lineCapStyle = .Round;

        MightyMindersUI.white.setStroke()
        bezier3Path.lineWidth = 2
        bezier3Path.stroke()
    }

    public class func drawLocationArrow(frame frame: CGRect = CGRect(x: 0, y: 0, width: 106, height: 106), active: Bool = false, pressed: Bool = false) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Subframes
        let group: CGRect = CGRect(x: frame.minX + 16.5, y: frame.minY + 23.5, width: frame.width - 56, height: frame.height - 53)


        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRect(x: frame.minX + 3, y: frame.minY + 3, width: frame.width - 16, height: frame.height - 16))
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, MightyMindersUI.lowShadow.shadowOffset, MightyMindersUI.lowShadow.shadowBlurRadius, (MightyMindersUI.lowShadow.shadowColor as! UIColor).CGColor)
        MightyMindersUI.white.setFill()
        ovalPath.fill()
        CGContextRestoreGState(context)

        MightyMindersUI.grey.setStroke()
        ovalPath.lineWidth = 1
        ovalPath.stroke()


        if (pressed) {
            //// Oval pressed Drawing
            let ovalPressedPath = UIBezierPath(ovalInRect: CGRect(x: frame.minX + 3, y: frame.minY + 3, width: frame.width - 16, height: frame.height - 16))
            MightyMindersUI.lightGrey.setFill()
            ovalPressedPath.fill()
            MightyMindersUI.grey.setStroke()
            ovalPressedPath.lineWidth = 1
            ovalPressedPath.stroke()
        }


        //// Group
        //// Bezier off Drawing
        let bezierOffPath = UIBezierPath()
        bezierOffPath.moveToPoint(CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 0.00000 * group.height))
        bezierOffPath.addCurveToPoint(CGPoint(x: group.minX + 0.99840 * group.width, y: group.minY + 0.00334 * group.height), controlPoint1: CGPoint(x: group.minX + 1.00003 * group.width, y: group.minY + -0.00005 * group.height), controlPoint2: CGPoint(x: group.minX + 0.99947 * group.width, y: group.minY + 0.00110 * group.height))
        bezierOffPath.addLineToPoint(CGPoint(x: group.minX + 0.37405 * group.width, y: group.minY + 0.64591 * group.height))
        bezierOffPath.addCurveToPoint(CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.52828 * group.height), controlPoint1: CGPoint(x: group.minX + 0.26506 * group.width, y: group.minY + 0.61163 * group.height), controlPoint2: CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.52828 * group.height))
        bezierOffPath.addCurveToPoint(CGPoint(x: group.minX + 0.99725 * group.width, y: group.minY + 0.00141 * group.height), controlPoint1: CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.52828 * group.height), controlPoint2: CGPoint(x: group.minX + 0.93956 * group.width, y: group.minY + 0.03189 * group.height))
        bezierOffPath.addLineToPoint(CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 0.00000 * group.height))
        bezierOffPath.closePath()
        bezierOffPath.moveToPoint(CGPoint(x: group.minX + 0.52032 * group.width, y: group.minY + 0.99935 * group.height))
        bezierOffPath.addCurveToPoint(CGPoint(x: group.minX + 0.42001 * group.width, y: group.minY + 0.66036 * group.height), controlPoint1: CGPoint(x: group.minX + 0.52001 * group.width, y: group.minY + 1.00000 * group.height), controlPoint2: CGPoint(x: group.minX + 0.42001 * group.width, y: group.minY + 0.66036 * group.height))
        bezierOffPath.addCurveToPoint(CGPoint(x: group.minX + 0.99606 * group.width, y: group.minY + 0.00821 * group.height), controlPoint1: CGPoint(x: group.minX + 0.42001 * group.width, y: group.minY + 0.66036 * group.height), controlPoint2: CGPoint(x: group.minX + 0.88433 * group.width, y: group.minY + 0.13470 * group.height))
        bezierOffPath.addCurveToPoint(CGPoint(x: group.minX + 0.52001 * group.width, y: group.minY + 1.00000 * group.height), controlPoint1: CGPoint(x: group.minX + 0.95009 * group.width, y: group.minY + 0.10399 * group.height), controlPoint2: CGPoint(x: group.minX + 0.52001 * group.width, y: group.minY + 1.00000 * group.height))
        bezierOffPath.addLineToPoint(CGPoint(x: group.minX + 0.52032 * group.width, y: group.minY + 0.99935 * group.height))
        bezierOffPath.closePath()
        MightyMindersUI.grey.setFill()
        bezierOffPath.fill()


        if (active) {
            //// Bezier Drawing
            let bezierPath = UIBezierPath()
            bezierPath.moveToPoint(CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 0.00000 * group.height))
            bezierPath.addCurveToPoint(CGPoint(x: group.minX + 0.99840 * group.width, y: group.minY + 0.00334 * group.height), controlPoint1: CGPoint(x: group.minX + 1.00003 * group.width, y: group.minY + -0.00005 * group.height), controlPoint2: CGPoint(x: group.minX + 0.99947 * group.width, y: group.minY + 0.00110 * group.height))
            bezierPath.addLineToPoint(CGPoint(x: group.minX + 0.37405 * group.width, y: group.minY + 0.64591 * group.height))
            bezierPath.addCurveToPoint(CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.52828 * group.height), controlPoint1: CGPoint(x: group.minX + 0.26506 * group.width, y: group.minY + 0.61163 * group.height), controlPoint2: CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.52828 * group.height))
            bezierPath.addCurveToPoint(CGPoint(x: group.minX + 0.99725 * group.width, y: group.minY + 0.00141 * group.height), controlPoint1: CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.52828 * group.height), controlPoint2: CGPoint(x: group.minX + 0.93956 * group.width, y: group.minY + 0.03189 * group.height))
            bezierPath.addLineToPoint(CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 0.00000 * group.height))
            bezierPath.closePath()
            bezierPath.moveToPoint(CGPoint(x: group.minX + 0.52032 * group.width, y: group.minY + 0.99935 * group.height))
            bezierPath.addCurveToPoint(CGPoint(x: group.minX + 0.42001 * group.width, y: group.minY + 0.66036 * group.height), controlPoint1: CGPoint(x: group.minX + 0.52001 * group.width, y: group.minY + 1.00000 * group.height), controlPoint2: CGPoint(x: group.minX + 0.42001 * group.width, y: group.minY + 0.66036 * group.height))
            bezierPath.addCurveToPoint(CGPoint(x: group.minX + 0.99606 * group.width, y: group.minY + 0.00821 * group.height), controlPoint1: CGPoint(x: group.minX + 0.42001 * group.width, y: group.minY + 0.66036 * group.height), controlPoint2: CGPoint(x: group.minX + 0.88433 * group.width, y: group.minY + 0.13470 * group.height))
            bezierPath.addCurveToPoint(CGPoint(x: group.minX + 0.52001 * group.width, y: group.minY + 1.00000 * group.height), controlPoint1: CGPoint(x: group.minX + 0.95009 * group.width, y: group.minY + 0.10399 * group.height), controlPoint2: CGPoint(x: group.minX + 0.52001 * group.width, y: group.minY + 1.00000 * group.height))
            bezierPath.addLineToPoint(CGPoint(x: group.minX + 0.52032 * group.width, y: group.minY + 0.99935 * group.height))
            bezierPath.closePath()
            MightyMindersUI.green.setFill()
            bezierPath.fill()
        }
    }

    public class func drawReminderList(frame frame: CGRect = CGRect(x: 0, y: 0, width: 99, height: 77), pressed: Bool = false) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Subframes
        let group5: CGRect = CGRect(x: frame.minX + 25.5, y: frame.minY + 17.5, width: frame.width - 57.5, height: frame.height - 42)


        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRect(x: frame.minX + 6.5, y: frame.minY + 6.5, width: frame.width - 20, height: frame.height - 20), cornerRadius: 10)
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, MightyMindersUI.lowShadow.shadowOffset, MightyMindersUI.lowShadow.shadowBlurRadius, (MightyMindersUI.lowShadow.shadowColor as! UIColor).CGColor)
        MightyMindersUI.white.setFill()
        rectanglePath.fill()
        CGContextRestoreGState(context)

        MightyMindersUI.lightGrey.setStroke()
        rectanglePath.lineWidth = 1
        rectanglePath.stroke()


        if (pressed) {
            //// Rectangle pressed Drawing
            let rectanglePressedPath = UIBezierPath(roundedRect: CGRect(x: frame.minX + 6.5, y: frame.minY + 6.5, width: frame.width - 20, height: frame.height - 20), cornerRadius: 10)
            MightyMindersUI.lightGrey.setFill()
            rectanglePressedPath.fill()
            MightyMindersUI.lightGrey.setStroke()
            rectanglePressedPath.lineWidth = 1
            rectanglePressedPath.stroke()
        }


        //// Group 5
        //// Group
        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRect(x: group5.minX + floor(group5.width * 0.00000 + 0.5), y: group5.minY + floor(group5.height * 0.00000 + 0.5), width: floor(group5.width * 0.09639 + 0.5) - floor(group5.width * 0.00000 + 0.5), height: floor(group5.height * 0.14286 + 0.5) - floor(group5.height * 0.00000 + 0.5)))
        MightyMindersUI.grey.setFill()
        ovalPath.fill()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPoint(x: group5.minX + 0.14563 * group5.width, y: group5.minY + 0.07143 * group5.height))
        bezierPath.addLineToPoint(CGPoint(x: group5.minX + 1.00000 * group5.width, y: group5.minY + 0.07143 * group5.height))
        bezierPath.lineCapStyle = .Round;

        MightyMindersUI.grey.setFill()
        bezierPath.fill()
        MightyMindersUI.grey.setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()




        //// Group 2
        //// Oval 2 Drawing
        let oval2Path = UIBezierPath(ovalInRect: CGRect(x: group5.minX + floor(group5.width * 0.00000 + 0.5), y: group5.minY + floor(group5.height * 0.42857 + 0.5), width: floor(group5.width * 0.09639 + 0.5) - floor(group5.width * 0.00000 + 0.5), height: floor(group5.height * 0.57143 + 0.5) - floor(group5.height * 0.42857 + 0.5)))
        MightyMindersUI.grey.setFill()
        oval2Path.fill()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPoint(x: group5.minX + 0.14563 * group5.width, y: group5.minY + 0.50000 * group5.height))
        bezier2Path.addLineToPoint(CGPoint(x: group5.minX + 1.00000 * group5.width, y: group5.minY + 0.50000 * group5.height))
        bezier2Path.lineCapStyle = .Round;

        MightyMindersUI.grey.setFill()
        bezier2Path.fill()
        MightyMindersUI.grey.setStroke()
        bezier2Path.lineWidth = 1
        bezier2Path.stroke()




        //// Group 3
        //// Oval 3 Drawing
        let oval3Path = UIBezierPath(ovalInRect: CGRect(x: group5.minX + floor(group5.width * 0.00000 + 0.5), y: group5.minY + floor(group5.height * 0.85714 + 0.5), width: floor(group5.width * 0.09639 + 0.5) - floor(group5.width * 0.00000 + 0.5), height: floor(group5.height * 1.00000 + 0.5) - floor(group5.height * 0.85714 + 0.5)))
        MightyMindersUI.grey.setFill()
        oval3Path.fill()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPoint(x: group5.minX + 0.14563 * group5.width, y: group5.minY + 0.92857 * group5.height))
        bezier3Path.addLineToPoint(CGPoint(x: group5.minX + 1.00000 * group5.width, y: group5.minY + 0.92857 * group5.height))
        bezier3Path.lineCapStyle = .Round;

        MightyMindersUI.grey.setFill()
        bezier3Path.fill()
        MightyMindersUI.grey.setStroke()
        bezier3Path.lineWidth = 1
        bezier3Path.stroke()
    }

    public class func drawSearchButton(frame frame: CGRect = CGRect(x: 0, y: 0, width: 106, height: 106), pressed: Bool = false) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Subframes
        let group: CGRect = CGRect(x: frame.minX + 21.5, y: frame.minY + 21.5, width: frame.width - 53, height: frame.height - 53)


        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRect(x: frame.minX + 3, y: frame.minY + 3, width: frame.width - 16, height: frame.height - 16))
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, MightyMindersUI.lowShadow.shadowOffset, MightyMindersUI.lowShadow.shadowBlurRadius, (MightyMindersUI.lowShadow.shadowColor as! UIColor).CGColor)
        MightyMindersUI.white.setFill()
        ovalPath.fill()
        CGContextRestoreGState(context)

        MightyMindersUI.grey.setStroke()
        ovalPath.lineWidth = 1
        ovalPath.stroke()


        if (pressed) {
            //// Oval pressed Drawing
            let ovalPressedPath = UIBezierPath(ovalInRect: CGRect(x: frame.minX + 3, y: frame.minY + 3, width: frame.width - 16, height: frame.height - 16))
            MightyMindersUI.lightGrey.setFill()
            ovalPressedPath.fill()
            MightyMindersUI.grey.setStroke()
            ovalPressedPath.lineWidth = 1
            ovalPressedPath.stroke()
        }


        //// Group
        //// Oval 2 Drawing
        let oval2Path = UIBezierPath(ovalInRect: CGRect(x: group.minX + floor(group.width * 0.00000 + 0.5), y: group.minY + floor(group.height * 0.00000 + 0.5), width: floor(group.width * 0.88679 + 0.5) - floor(group.width * 0.00000 + 0.5), height: floor(group.height * 0.79245 + 0.5) - floor(group.height * 0.00000 + 0.5)))
        MightyMindersUI.lightGrey.setFill()
        oval2Path.fill()
        MightyMindersUI.grey.setStroke()
        oval2Path.lineWidth = 3
        oval2Path.stroke()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPoint(x: group.minX + 0.70000 * group.width, y: group.minY + 0.69643 * group.height))
        bezierPath.addLineToPoint(CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 1.00000 * group.height))
        MightyMindersUI.grey.setStroke()
        bezierPath.lineWidth = 8
        bezierPath.stroke()
    }

    public class func drawFriendsButton(frame frame: CGRect = CGRect(x: 0, y: 0, width: 213, height: 81)) {


        //// Subframes
        let group: CGRect = CGRect(x: frame.minX + floor(frame.width * 0.03286 + 0.5), y: frame.minY + floor(frame.height * 0.06173) + 0.5, width: floor(frame.width * 0.35681 + 0.5) - floor(frame.width * 0.03286 + 0.5), height: floor(frame.height * 0.94444 + 0.5) - floor(frame.height * 0.06173) - 0.5)
        let group2: CGRect = CGRect(x: frame.minX + floor(frame.width * 0.41089 - 0.02) + 0.52, y: frame.minY + floor(frame.height * 0.49395 - 0.01) + 0.51, width: floor(frame.width * 0.91124 + 0.4) - floor(frame.width * 0.41089 - 0.02) - 0.42, height: floor(frame.height * 0.79617 - 0.49) - floor(frame.height * 0.49395 - 0.01) + 0.48)


        //// Group
        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPoint(x: group.minX + 0.58696 * group.width, y: group.minY + 0.31544 * group.height))
        bezier3Path.addCurveToPoint(CGPoint(x: group.minX + 0.41802 * group.width, y: group.minY + 0.53692 * group.height), controlPoint1: CGPoint(x: group.minX + 0.58696 * group.width, y: group.minY + 0.41766 * group.height), controlPoint2: CGPoint(x: group.minX + 0.51645 * group.width, y: group.minY + 0.50464 * group.height))
        bezier3Path.addCurveToPoint(CGPoint(x: group.minX + 0.56522 * group.width, y: group.minY + 0.63758 * group.height), controlPoint1: CGPoint(x: group.minX + 0.48123 * group.width, y: group.minY + 0.58015 * group.height), controlPoint2: CGPoint(x: group.minX + 0.56522 * group.width, y: group.minY + 0.63758 * group.height))
        bezier3Path.addLineToPoint(CGPoint(x: group.minX + 0.68116 * group.width, y: group.minY + 1.00000 * group.height))
        bezier3Path.addLineToPoint(CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 1.00000 * group.height))
        bezier3Path.addLineToPoint(CGPoint(x: group.minX + 0.11594 * group.width, y: group.minY + 0.63758 * group.height))
        bezier3Path.addCurveToPoint(CGPoint(x: group.minX + 0.26676 * group.width, y: group.minY + 0.54216 * group.height), controlPoint1: CGPoint(x: group.minX + 0.11594 * group.width, y: group.minY + 0.63758 * group.height), controlPoint2: CGPoint(x: group.minX + 0.19962 * group.width, y: group.minY + 0.58464 * group.height))
        bezier3Path.addCurveToPoint(CGPoint(x: group.minX + 0.07971 * group.width, y: group.minY + 0.31544 * group.height), controlPoint1: CGPoint(x: group.minX + 0.15898 * group.width, y: group.minY + 0.51508 * group.height), controlPoint2: CGPoint(x: group.minX + 0.07971 * group.width, y: group.minY + 0.42383 * group.height))
        bezier3Path.addCurveToPoint(CGPoint(x: group.minX + 0.21414 * group.width, y: group.minY + 0.10804 * group.height), controlPoint1: CGPoint(x: group.minX + 0.07971 * group.width, y: group.minY + 0.22561 * group.height), controlPoint2: CGPoint(x: group.minX + 0.13415 * group.width, y: group.minY + 0.14755 * group.height))
        bezier3Path.addCurveToPoint(CGPoint(x: group.minX + 0.33333 * group.width, y: group.minY + 0.08054 * group.height), controlPoint1: CGPoint(x: group.minX + 0.24968 * group.width, y: group.minY + 0.09049 * group.height), controlPoint2: CGPoint(x: group.minX + 0.29025 * group.width, y: group.minY + 0.08054 * group.height))
        bezier3Path.addCurveToPoint(CGPoint(x: group.minX + 0.58696 * group.width, y: group.minY + 0.31544 * group.height), controlPoint1: CGPoint(x: group.minX + 0.47341 * group.width, y: group.minY + 0.08054 * group.height), controlPoint2: CGPoint(x: group.minX + 0.58696 * group.width, y: group.minY + 0.18570 * group.height))
        bezier3Path.closePath()
        MightyMindersUI.lightGrey.setFill()
        bezier3Path.fill()
        MightyMindersUI.grey.setStroke()
        bezier3Path.lineWidth = 1
        bezier3Path.stroke()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPoint(x: group.minX + 0.90580 * group.width, y: group.minY + 0.23490 * group.height))
        bezier4Path.addCurveToPoint(CGPoint(x: group.minX + 0.73686 * group.width, y: group.minY + 0.45638 * group.height), controlPoint1: CGPoint(x: group.minX + 0.90580 * group.width, y: group.minY + 0.33713 * group.height), controlPoint2: CGPoint(x: group.minX + 0.83529 * group.width, y: group.minY + 0.42410 * group.height))
        bezier4Path.addCurveToPoint(CGPoint(x: group.minX + 0.88406 * group.width, y: group.minY + 0.55705 * group.height), controlPoint1: CGPoint(x: group.minX + 0.80007 * group.width, y: group.minY + 0.49961 * group.height), controlPoint2: CGPoint(x: group.minX + 0.88406 * group.width, y: group.minY + 0.55705 * group.height))
        bezier4Path.addLineToPoint(CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 0.91946 * group.height))
        bezier4Path.addLineToPoint(CGPoint(x: group.minX + 0.82770 * group.width, y: group.minY + 0.91946 * group.height))
        bezier4Path.addCurveToPoint(CGPoint(x: group.minX + 0.72464 * group.width, y: group.minY + 0.59732 * group.height), controlPoint1: CGPoint(x: group.minX + 0.79749 * group.width, y: group.minY + 0.82504 * group.height), controlPoint2: CGPoint(x: group.minX + 0.72464 * group.width, y: group.minY + 0.59732 * group.height))
        bezier4Path.addCurveToPoint(CGPoint(x: group.minX + 0.57744 * group.width, y: group.minY + 0.49665 * group.height), controlPoint1: CGPoint(x: group.minX + 0.72464 * group.width, y: group.minY + 0.59732 * group.height), controlPoint2: CGPoint(x: group.minX + 0.64065 * group.width, y: group.minY + 0.53988 * group.height))
        bezier4Path.addCurveToPoint(CGPoint(x: group.minX + 0.74638 * group.width, y: group.minY + 0.27517 * group.height), controlPoint1: CGPoint(x: group.minX + 0.67587 * group.width, y: group.minY + 0.46437 * group.height), controlPoint2: CGPoint(x: group.minX + 0.74638 * group.width, y: group.minY + 0.37739 * group.height))
        bezier4Path.addCurveToPoint(CGPoint(x: group.minX + 0.50936 * group.width, y: group.minY + 0.04076 * group.height), controlPoint1: CGPoint(x: group.minX + 0.74638 * group.width, y: group.minY + 0.15060 * group.height), controlPoint2: CGPoint(x: group.minX + 0.64169 * group.width, y: group.minY + 0.04868 * group.height))
        bezier4Path.addCurveToPoint(CGPoint(x: group.minX + 0.53298 * group.width, y: group.minY + 0.02750 * group.height), controlPoint1: CGPoint(x: group.minX + 0.51694 * group.width, y: group.minY + 0.03596 * group.height), controlPoint2: CGPoint(x: group.minX + 0.52483 * group.width, y: group.minY + 0.03153 * group.height))
        bezier4Path.addCurveToPoint(CGPoint(x: group.minX + 0.65217 * group.width, y: group.minY + 0.00000 * group.height), controlPoint1: CGPoint(x: group.minX + 0.56852 * group.width, y: group.minY + 0.00995 * group.height), controlPoint2: CGPoint(x: group.minX + 0.60909 * group.width, y: group.minY + 0.00000 * group.height))
        bezier4Path.addCurveToPoint(CGPoint(x: group.minX + 0.90580 * group.width, y: group.minY + 0.23490 * group.height), controlPoint1: CGPoint(x: group.minX + 0.79225 * group.width, y: group.minY + 0.00000 * group.height), controlPoint2: CGPoint(x: group.minX + 0.90580 * group.width, y: group.minY + 0.10517 * group.height))
        bezier4Path.closePath()
        MightyMindersUI.lightGrey.setFill()
        bezier4Path.fill()
        MightyMindersUI.grey.setStroke()
        bezier4Path.lineWidth = 1
        bezier4Path.stroke()




        //// Group 2
        //// Text Drawing
        let textPath = UIBezierPath()
        textPath.moveToPoint(CGPoint(x: group2.minX + 0.00000 * group2.width, y: group2.minY + 0.00000 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.00000 * group2.width, y: group2.minY + 0.98077 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.02233 * group2.width, y: group2.minY + 0.98077 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.02233 * group2.width, y: group2.minY + 0.51374 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.13465 * group2.width, y: group2.minY + 0.51374 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.13465 * group2.width, y: group2.minY + 0.43407 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.02233 * group2.width, y: group2.minY + 0.43407 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.02233 * group2.width, y: group2.minY + 0.07967 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.14877 * group2.width, y: group2.minY + 0.07967 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.14877 * group2.width, y: group2.minY + 0.00000 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.00000 * group2.width, y: group2.minY + 0.00000 * group2.height))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: group2.minX + 0.17241 * group2.width, y: group2.minY + 0.27198 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.17241 * group2.width, y: group2.minY + 0.98077 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.19310 * group2.width, y: group2.minY + 0.98077 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.19310 * group2.width, y: group2.minY + 0.60302 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.19770 * group2.width, y: group2.minY + 0.49931 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.19310 * group2.width, y: group2.minY + 0.56548 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.19464 * group2.width, y: group2.minY + 0.53091 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.21067 * group2.width, y: group2.minY + 0.41758 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.20077 * group2.width, y: group2.minY + 0.46772 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.20509 * group2.width, y: group2.minY + 0.44048 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.23054 * group2.width, y: group2.minY + 0.36470 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.21626 * group2.width, y: group2.minY + 0.39469 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.22288 * group2.width, y: group2.minY + 0.37706 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.25616 * group2.width, y: group2.minY + 0.34890 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.23820 * group2.width, y: group2.minY + 0.35234 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.24674 * group2.width, y: group2.minY + 0.34707 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.25616 * group2.width, y: group2.minY + 0.26236 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.21658 * group2.width, y: group2.minY + 0.30495 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.24083 * group2.width, y: group2.minY + 0.25962 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.22764 * group2.width, y: group2.minY + 0.27381 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.19212 * group2.width, y: group2.minY + 0.43819 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.20553 * group2.width, y: group2.minY + 0.33608 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.19737 * group2.width, y: group2.minY + 0.38049 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.19146 * group2.width, y: group2.minY + 0.43819 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.19146 * group2.width, y: group2.minY + 0.27198 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.17241 * group2.width, y: group2.minY + 0.27198 * group2.height))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: group2.minX + 0.27619 * group2.width, y: group2.minY + 0.00000 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.27619 * group2.width, y: group2.minY + 0.13874 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.29688 * group2.width, y: group2.minY + 0.13874 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.29688 * group2.width, y: group2.minY + 0.00000 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.27619 * group2.width, y: group2.minY + 0.00000 * group2.height))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: group2.minX + 0.27619 * group2.width, y: group2.minY + 0.27198 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.27619 * group2.width, y: group2.minY + 0.98077 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.29688 * group2.width, y: group2.minY + 0.98077 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.29688 * group2.width, y: group2.minY + 0.27198 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.27619 * group2.width, y: group2.minY + 0.27198 * group2.height))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: group2.minX + 0.45846 * group2.width, y: group2.minY + 0.57692 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.34877 * group2.width, y: group2.minY + 0.57692 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.35419 * group2.width, y: group2.minY + 0.48283 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.34964 * group2.width, y: group2.minY + 0.54487 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.35145 * group2.width, y: group2.minY + 0.51351 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.36519 * group2.width, y: group2.minY + 0.40179 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.35692 * group2.width, y: group2.minY + 0.45215 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.36059 * group2.width, y: group2.minY + 0.42514 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.38194 * group2.width, y: group2.minY + 0.34547 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.36979 * group2.width, y: group2.minY + 0.37843 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.37537 * group2.width, y: group2.minY + 0.35966 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.40460 * group2.width, y: group2.minY + 0.32418 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.38851 * group2.width, y: group2.minY + 0.33127 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.39606 * group2.width, y: group2.minY + 0.32418 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.42693 * group2.width, y: group2.minY + 0.34547 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.41292 * group2.width, y: group2.minY + 0.32418 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.42036 * group2.width, y: group2.minY + 0.33127 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.44368 * group2.width, y: group2.minY + 0.40179 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.43350 * group2.width, y: group2.minY + 0.35966 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.43908 * group2.width, y: group2.minY + 0.37843 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.45435 * group2.width, y: group2.minY + 0.48214 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.44828 * group2.width, y: group2.minY + 0.42514 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.45183 * group2.width, y: group2.minY + 0.45192 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.45846 * group2.width, y: group2.minY + 0.57692 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.45687 * group2.width, y: group2.minY + 0.51236 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.45824 * group2.width, y: group2.minY + 0.54396 * group2.height))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: group2.minX + 0.34877 * group2.width, y: group2.minY + 0.64973 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.47915 * group2.width, y: group2.minY + 0.64973 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.47586 * group2.width, y: group2.minY + 0.50343 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.47958 * group2.width, y: group2.minY + 0.60027 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.47849 * group2.width, y: group2.minY + 0.55151 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.46289 * group2.width, y: group2.minY + 0.37569 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.47323 * group2.width, y: group2.minY + 0.45536 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.46891 * group2.width, y: group2.minY + 0.41277 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.43941 * group2.width, y: group2.minY + 0.28571 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.45687 * group2.width, y: group2.minY + 0.33860 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.44904 * group2.width, y: group2.minY + 0.30861 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.40460 * group2.width, y: group2.minY + 0.25137 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.42978 * group2.width, y: group2.minY + 0.26282 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.41817 * group2.width, y: group2.minY + 0.25137 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.36995 * group2.width, y: group2.minY + 0.28365 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.39124 * group2.width, y: group2.minY + 0.25137 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.37969 * group2.width, y: group2.minY + 0.26213 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.34614 * group2.width, y: group2.minY + 0.36882 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.36021 * group2.width, y: group2.minY + 0.30517 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.35227 * group2.width, y: group2.minY + 0.33356 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.33251 * group2.width, y: group2.minY + 0.48901 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.34001 * group2.width, y: group2.minY + 0.40408 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.33547 * group2.width, y: group2.minY + 0.44414 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.32808 * group2.width, y: group2.minY + 0.62637 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.32956 * group2.width, y: group2.minY + 0.53388 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.32808 * group2.width, y: group2.minY + 0.57967 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.33251 * group2.width, y: group2.minY + 0.76992 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.32808 * group2.width, y: group2.minY + 0.67674 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.32956 * group2.width, y: group2.minY + 0.72459 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.34614 * group2.width, y: group2.minY + 0.88942 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.33547 * group2.width, y: group2.minY + 0.81525 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.34001 * group2.width, y: group2.minY + 0.85508 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.36995 * group2.width, y: group2.minY + 0.97047 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.35227 * group2.width, y: group2.minY + 0.92376 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.36021 * group2.width, y: group2.minY + 0.95078 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.40460 * group2.width, y: group2.minY + 1.00000 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.37969 * group2.width, y: group2.minY + 0.99016 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.39124 * group2.width, y: group2.minY + 1.00000 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.45435 * group2.width, y: group2.minY + 0.93407 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.42605 * group2.width, y: group2.minY + 1.00000 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.44264 * group2.width, y: group2.minY + 0.97802 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.47849 * group2.width, y: group2.minY + 0.74725 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.46606 * group2.width, y: group2.minY + 0.89011 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.47411 * group2.width, y: group2.minY + 0.82784 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.45780 * group2.width, y: group2.minY + 0.74725 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.44007 * group2.width, y: group2.minY + 0.87912 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.45452 * group2.width, y: group2.minY + 0.80220 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.44860 * group2.width, y: group2.minY + 0.84615 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.40460 * group2.width, y: group2.minY + 0.92857 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.43153 * group2.width, y: group2.minY + 0.91209 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.41970 * group2.width, y: group2.minY + 0.92857 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.37931 * group2.width, y: group2.minY + 0.90247 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.39475 * group2.width, y: group2.minY + 0.92857 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.38632 * group2.width, y: group2.minY + 0.91987 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.36190 * group2.width, y: group2.minY + 0.83654 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.37230 * group2.width, y: group2.minY + 0.88507 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.36650 * group2.width, y: group2.minY + 0.86310 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.35189 * group2.width, y: group2.minY + 0.74657 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.35731 * group2.width, y: group2.minY + 0.80998 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.35397 * group2.width, y: group2.minY + 0.77999 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.34877 * group2.width, y: group2.minY + 0.64973 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.34981 * group2.width, y: group2.minY + 0.71314 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.34877 * group2.width, y: group2.minY + 0.68086 * group2.height))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: group2.minX + 0.50673 * group2.width, y: group2.minY + 0.27198 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.50673 * group2.width, y: group2.minY + 0.98077 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.52742 * group2.width, y: group2.minY + 0.98077 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.52742 * group2.width, y: group2.minY + 0.56731 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.53153 * group2.width, y: group2.minY + 0.47047 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.52764 * group2.width, y: group2.minY + 0.53251 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.52901 * group2.width, y: group2.minY + 0.50023 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.54204 * group2.width, y: group2.minY + 0.39354 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.53404 * group2.width, y: group2.minY + 0.44070 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.53755 * group2.width, y: group2.minY + 0.41506 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.55846 * group2.width, y: group2.minY + 0.34272 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.54652 * group2.width, y: group2.minY + 0.37202 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.55200 * group2.width, y: group2.minY + 0.35508 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.58062 * group2.width, y: group2.minY + 0.32418 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.56492 * group2.width, y: group2.minY + 0.33036 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.57230 * group2.width, y: group2.minY + 0.32418 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.60148 * group2.width, y: group2.minY + 0.34066 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.58894 * group2.width, y: group2.minY + 0.32418 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.59589 * group2.width, y: group2.minY + 0.32967 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.61478 * group2.width, y: group2.minY + 0.38599 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.60706 * group2.width, y: group2.minY + 0.35165 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.61149 * group2.width, y: group2.minY + 0.36676 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.62167 * group2.width, y: group2.minY + 0.45398 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.61806 * group2.width, y: group2.minY + 0.40522 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.62036 * group2.width, y: group2.minY + 0.42788 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.62365 * group2.width, y: group2.minY + 0.53846 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.62299 * group2.width, y: group2.minY + 0.48008 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.62365 * group2.width, y: group2.minY + 0.50824 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.62365 * group2.width, y: group2.minY + 0.98077 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.64433 * group2.width, y: group2.minY + 0.98077 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.64433 * group2.width, y: group2.minY + 0.52473 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.64138 * group2.width, y: group2.minY + 0.41071 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.64433 * group2.width, y: group2.minY + 0.48260 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.64335 * group2.width, y: group2.minY + 0.44460 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.63120 * group2.width, y: group2.minY + 0.32486 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.63941 * group2.width, y: group2.minY + 0.37683 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.63602 * group2.width, y: group2.minY + 0.34821 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.61199 * group2.width, y: group2.minY + 0.27060 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.62638 * group2.width, y: group2.minY + 0.30151 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.61998 * group2.width, y: group2.minY + 0.28342 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.58227 * group2.width, y: group2.minY + 0.25137 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.60400 * group2.width, y: group2.minY + 0.25778 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.59409 * group2.width, y: group2.minY + 0.25137 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.54910 * group2.width, y: group2.minY + 0.29052 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.57022 * group2.width, y: group2.minY + 0.25137 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.55917 * group2.width, y: group2.minY + 0.26442 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.52808 * group2.width, y: group2.minY + 0.39423 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.53903 * group2.width, y: group2.minY + 0.31662 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.53202 * group2.width, y: group2.minY + 0.35119 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.52742 * group2.width, y: group2.minY + 0.39423 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.52742 * group2.width, y: group2.minY + 0.27198 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.50673 * group2.width, y: group2.minY + 0.27198 * group2.height))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: group2.minX + 0.83251 * group2.width, y: group2.minY + 0.98077 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.83251 * group2.width, y: group2.minY + 0.00000 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.81182 * group2.width, y: group2.minY + 0.00000 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.81182 * group2.width, y: group2.minY + 0.40659 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.81117 * group2.width, y: group2.minY + 0.40659 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.80181 * group2.width, y: group2.minY + 0.33929 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.80898 * group2.width, y: group2.minY + 0.38095 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.80586 * group2.width, y: group2.minY + 0.35852 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.78785 * group2.width, y: group2.minY + 0.29052 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.79776 * group2.width, y: group2.minY + 0.32005 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.79310 * group2.width, y: group2.minY + 0.30380 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.77094 * group2.width, y: group2.minY + 0.26099 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.78259 * group2.width, y: group2.minY + 0.27724 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.77696 * group2.width, y: group2.minY + 0.26740 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.75238 * group2.width, y: group2.minY + 0.25137 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.76492 * group2.width, y: group2.minY + 0.25458 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.75873 * group2.width, y: group2.minY + 0.25137 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.71872 * group2.width, y: group2.minY + 0.28159 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.73946 * group2.width, y: group2.minY + 0.25137 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.72824 * group2.width, y: group2.minY + 0.26145 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.69491 * group2.width, y: group2.minY + 0.36332 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.70920 * group2.width, y: group2.minY + 0.30174 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.70126 * group2.width, y: group2.minY + 0.32898 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.68079 * group2.width, y: group2.minY + 0.48283 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.68856 * group2.width, y: group2.minY + 0.39767 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.68385 * group2.width, y: group2.minY + 0.43750 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.67619 * group2.width, y: group2.minY + 0.62637 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.67772 * group2.width, y: group2.minY + 0.52816 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.67619 * group2.width, y: group2.minY + 0.57601 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.68079 * group2.width, y: group2.minY + 0.76992 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.67619 * group2.width, y: group2.minY + 0.67674 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.67772 * group2.width, y: group2.minY + 0.72459 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.69491 * group2.width, y: group2.minY + 0.88942 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.68385 * group2.width, y: group2.minY + 0.81525 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.68856 * group2.width, y: group2.minY + 0.85508 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.71872 * group2.width, y: group2.minY + 0.97047 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.70126 * group2.width, y: group2.minY + 0.92376 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.70920 * group2.width, y: group2.minY + 0.95078 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.75238 * group2.width, y: group2.minY + 1.00000 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.72824 * group2.width, y: group2.minY + 0.99016 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.73946 * group2.width, y: group2.minY + 1.00000 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.77094 * group2.width, y: group2.minY + 0.98901 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.75851 * group2.width, y: group2.minY + 1.00000 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.76470 * group2.width, y: group2.minY + 0.99634 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.78851 * group2.width, y: group2.minY + 0.95810 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.77718 * group2.width, y: group2.minY + 0.98168 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.78303 * group2.width, y: group2.minY + 0.97138 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.80312 * group2.width, y: group2.minY + 0.90934 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.79398 * group2.width, y: group2.minY + 0.94483 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.79885 * group2.width, y: group2.minY + 0.92857 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.81281 * group2.width, y: group2.minY + 0.84615 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.80739 * group2.width, y: group2.minY + 0.89011 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.81062 * group2.width, y: group2.minY + 0.86905 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.81346 * group2.width, y: group2.minY + 0.84615 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.81346 * group2.width, y: group2.minY + 0.98077 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.83251 * group2.width, y: group2.minY + 0.98077 * group2.height))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: group2.minX + 0.69688 * group2.width, y: group2.minY + 0.62637 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.70000 * group2.width, y: group2.minY + 0.51717 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.69688 * group2.width, y: group2.minY + 0.58974 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.69792 * group2.width, y: group2.minY + 0.55334 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.70985 * group2.width, y: group2.minY + 0.42033 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.70208 * group2.width, y: group2.minY + 0.48100 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.70536 * group2.width, y: group2.minY + 0.44872 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.72709 * group2.width, y: group2.minY + 0.35096 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.71434 * group2.width, y: group2.minY + 0.39194 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.72009 * group2.width, y: group2.minY + 0.36882 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.75238 * group2.width, y: group2.minY + 0.32418 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.73410 * group2.width, y: group2.minY + 0.33310 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.74253 * group2.width, y: group2.minY + 0.32418 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.78013 * group2.width, y: group2.minY + 0.35096 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.76333 * group2.width, y: group2.minY + 0.32418 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.77258 * group2.width, y: group2.minY + 0.33310 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.79852 * group2.width, y: group2.minY + 0.42033 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.78768 * group2.width, y: group2.minY + 0.36882 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.79381 * group2.width, y: group2.minY + 0.39194 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.80870 * group2.width, y: group2.minY + 0.51717 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.80323 * group2.width, y: group2.minY + 0.44872 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.80662 * group2.width, y: group2.minY + 0.48100 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.81182 * group2.width, y: group2.minY + 0.62637 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.81078 * group2.width, y: group2.minY + 0.55334 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.81182 * group2.width, y: group2.minY + 0.58974 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.80870 * group2.width, y: group2.minY + 0.73558 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.81182 * group2.width, y: group2.minY + 0.66300 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.81078 * group2.width, y: group2.minY + 0.69940 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.79852 * group2.width, y: group2.minY + 0.83242 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.80662 * group2.width, y: group2.minY + 0.77175 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.80323 * group2.width, y: group2.minY + 0.80403 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.78013 * group2.width, y: group2.minY + 0.90179 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.79381 * group2.width, y: group2.minY + 0.86081 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.78768 * group2.width, y: group2.minY + 0.88393 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.75238 * group2.width, y: group2.minY + 0.92857 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.77258 * group2.width, y: group2.minY + 0.91964 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.76333 * group2.width, y: group2.minY + 0.92857 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.72709 * group2.width, y: group2.minY + 0.90179 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.74253 * group2.width, y: group2.minY + 0.92857 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.73410 * group2.width, y: group2.minY + 0.91964 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.70985 * group2.width, y: group2.minY + 0.83242 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.72009 * group2.width, y: group2.minY + 0.88393 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.71434 * group2.width, y: group2.minY + 0.86081 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.70000 * group2.width, y: group2.minY + 0.73558 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.70536 * group2.width, y: group2.minY + 0.80403 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.70208 * group2.width, y: group2.minY + 0.77175 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.69688 * group2.width, y: group2.minY + 0.62637 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.69792 * group2.width, y: group2.minY + 0.69940 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.69688 * group2.width, y: group2.minY + 0.66300 * group2.height))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: group2.minX + 0.97340 * group2.width, y: group2.minY + 0.47940 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.99409 * group2.width, y: group2.minY + 0.47940 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.98851 * group2.width, y: group2.minY + 0.37912 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.99365 * group2.width, y: group2.minY + 0.44093 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.99179 * group2.width, y: group2.minY + 0.40751 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.97521 * group2.width, y: group2.minY + 0.30769 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.98522 * group2.width, y: group2.minY + 0.35073 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.98079 * group2.width, y: group2.minY + 0.32692 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.95583 * group2.width, y: group2.minY + 0.26511 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.96962 * group2.width, y: group2.minY + 0.28846 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.96316 * group2.width, y: group2.minY + 0.27427 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.93202 * group2.width, y: group2.minY + 0.25137 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.94849 * group2.width, y: group2.minY + 0.25595 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.94056 * group2.width, y: group2.minY + 0.25137 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.90952 * group2.width, y: group2.minY + 0.26236 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.92458 * group2.width, y: group2.minY + 0.25137 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.91708 * group2.width, y: group2.minY + 0.25504 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.88900 * group2.width, y: group2.minY + 0.29670 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.90197 * group2.width, y: group2.minY + 0.26969 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.89513 * group2.width, y: group2.minY + 0.28114 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.87406 * group2.width, y: group2.minY + 0.35852 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.88287 * group2.width, y: group2.minY + 0.31227 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.87789 * group2.width, y: group2.minY + 0.33288 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.86831 * group2.width, y: group2.minY + 0.45055 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.87022 * group2.width, y: group2.minY + 0.38416 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.86831 * group2.width, y: group2.minY + 0.41483 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.87192 * group2.width, y: group2.minY + 0.52679 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.86831 * group2.width, y: group2.minY + 0.48077 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.86951 * group2.width, y: group2.minY + 0.50618 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.88194 * group2.width, y: group2.minY + 0.57898 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.87433 * group2.width, y: group2.minY + 0.54739 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.87767 * group2.width, y: group2.minY + 0.56479 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.89688 * group2.width, y: group2.minY + 0.61470 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.88621 * group2.width, y: group2.minY + 0.59318 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.89119 * group2.width, y: group2.minY + 0.60508 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.91560 * group2.width, y: group2.minY + 0.64011 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.90257 * group2.width, y: group2.minY + 0.62431 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.90881 * group2.width, y: group2.minY + 0.63278 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.94220 * group2.width, y: group2.minY + 0.66484 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.95583 * group2.width, y: group2.minY + 0.68132 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.94680 * group2.width, y: group2.minY + 0.66941 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.95134 * group2.width, y: group2.minY + 0.67491 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.96782 * group2.width, y: group2.minY + 0.70536 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.96032 * group2.width, y: group2.minY + 0.68773 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.96431 * group2.width, y: group2.minY + 0.69574 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.97619 * group2.width, y: group2.minY + 0.74107 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.97132 * group2.width, y: group2.minY + 0.71497 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.97411 * group2.width, y: group2.minY + 0.72688 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.97931 * group2.width, y: group2.minY + 0.79396 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.97827 * group2.width, y: group2.minY + 0.75527 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.97931 * group2.width, y: group2.minY + 0.77289 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.97488 * group2.width, y: group2.minY + 0.85646 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.97931 * group2.width, y: group2.minY + 0.81868 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.97783 * group2.width, y: group2.minY + 0.83951 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.96355 * group2.width, y: group2.minY + 0.89835 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.97192 * group2.width, y: group2.minY + 0.87340 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.96814 * group2.width, y: group2.minY + 0.88736 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.94860 * group2.width, y: group2.minY + 0.92170 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.95895 * group2.width, y: group2.minY + 0.90934 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.95397 * group2.width, y: group2.minY + 0.91712 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.93300 * group2.width, y: group2.minY + 0.92857 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.94324 * group2.width, y: group2.minY + 0.92628 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.93804 * group2.width, y: group2.minY + 0.92857 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.89836 * group2.width, y: group2.minY + 0.88393 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.91921 * group2.width, y: group2.minY + 0.92857 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.90766 * group2.width, y: group2.minY + 0.91369 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.88309 * group2.width, y: group2.minY + 0.75137 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.88905 * group2.width, y: group2.minY + 0.85417 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.88396 * group2.width, y: group2.minY + 0.80998 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.86240 * group2.width, y: group2.minY + 0.75137 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.88358 * group2.width, y: group2.minY + 0.94093 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.86415 * group2.width, y: group2.minY + 0.83837 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.87121 * group2.width, y: group2.minY + 0.90156 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.93202 * group2.width, y: group2.minY + 1.00000 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.89595 * group2.width, y: group2.minY + 0.98031 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.91210 * group2.width, y: group2.minY + 1.00000 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.95599 * group2.width, y: group2.minY + 0.98901 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.93990 * group2.width, y: group2.minY + 1.00000 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.94789 * group2.width, y: group2.minY + 0.99634 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.97783 * group2.width, y: group2.minY + 0.95261 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.96409 * group2.width, y: group2.minY + 0.98168 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.97137 * group2.width, y: group2.minY + 0.96955 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.99376 * group2.width, y: group2.minY + 0.88668 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.98429 * group2.width, y: group2.minY + 0.93567 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.98960 * group2.width, y: group2.minY + 0.91369 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 1.00000 * group2.width, y: group2.minY + 0.78846 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.99792 * group2.width, y: group2.minY + 0.85966 * group2.height), controlPoint2: CGPoint(x: group2.minX + 1.00000 * group2.width, y: group2.minY + 0.82692 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.99573 * group2.width, y: group2.minY + 0.70742 * group2.height), controlPoint1: CGPoint(x: group2.minX + 1.00000 * group2.width, y: group2.minY + 0.75733 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.99858 * group2.width, y: group2.minY + 0.73031 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.98473 * group2.width, y: group2.minY + 0.64973 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.99288 * group2.width, y: group2.minY + 0.68452 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.98922 * group2.width, y: group2.minY + 0.66529 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.96929 * group2.width, y: group2.minY + 0.61195 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.98024 * group2.width, y: group2.minY + 0.63416 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.97510 * group2.width, y: group2.minY + 0.62157 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.95172 * group2.width, y: group2.minY + 0.59203 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.96349 * group2.width, y: group2.minY + 0.60234 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.95764 * group2.width, y: group2.minY + 0.59570 * group2.height))
        textPath.addLineToPoint(CGPoint(x: group2.minX + 0.92414 * group2.width, y: group2.minY + 0.56593 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.91264 * group2.width, y: group2.minY + 0.55151 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.92063 * group2.width, y: group2.minY + 0.56227 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.91680 * group2.width, y: group2.minY + 0.55746 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.90115 * group2.width, y: group2.minY + 0.52885 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.90848 * group2.width, y: group2.minY + 0.54556 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.90465 * group2.width, y: group2.minY + 0.53800 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.89245 * group2.width, y: group2.minY + 0.49519 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.89765 * group2.width, y: group2.minY + 0.51969 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.89475 * group2.width, y: group2.minY + 0.50847 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.88900 * group2.width, y: group2.minY + 0.44643 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.89015 * group2.width, y: group2.minY + 0.48191 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.88900 * group2.width, y: group2.minY + 0.46566 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.89261 * group2.width, y: group2.minY + 0.38874 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.88900 * group2.width, y: group2.minY + 0.42353 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.89020 * group2.width, y: group2.minY + 0.40430 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.90213 * group2.width, y: group2.minY + 0.35096 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.89502 * group2.width, y: group2.minY + 0.37317 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.89819 * group2.width, y: group2.minY + 0.36058 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.91511 * group2.width, y: group2.minY + 0.33036 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.90608 * group2.width, y: group2.minY + 0.34135 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.91040 * group2.width, y: group2.minY + 0.33448 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.92906 * group2.width, y: group2.minY + 0.32418 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.91981 * group2.width, y: group2.minY + 0.32624 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.92447 * group2.width, y: group2.minY + 0.32418 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.94581 * group2.width, y: group2.minY + 0.33310 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.93498 * group2.width, y: group2.minY + 0.32418 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.94056 * group2.width, y: group2.minY + 0.32715 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.95977 * group2.width, y: group2.minY + 0.36126 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.95107 * group2.width, y: group2.minY + 0.33906 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.95572 * group2.width, y: group2.minY + 0.34844 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.96946 * group2.width, y: group2.minY + 0.41003 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.96382 * group2.width, y: group2.minY + 0.37408 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.96705 * group2.width, y: group2.minY + 0.39034 * group2.height))
        textPath.addCurveToPoint(CGPoint(x: group2.minX + 0.97340 * group2.width, y: group2.minY + 0.47940 * group2.height), controlPoint1: CGPoint(x: group2.minX + 0.97187 * group2.width, y: group2.minY + 0.42972 * group2.height), controlPoint2: CGPoint(x: group2.minX + 0.97318 * group2.width, y: group2.minY + 0.45284 * group2.height))
        textPath.closePath()
        MightyMindersUI.grey.setFill()
        textPath.fill()
    }

}



extension UIColor {
    func colorWithHue(newHue: CGFloat) -> UIColor {
        var saturation: CGFloat = 1.0, brightness: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(nil, saturation: &saturation, brightness: &brightness, alpha: &alpha)
        return UIColor(hue: newHue, saturation: saturation, brightness: brightness, alpha: alpha)
    }
    func colorWithSaturation(newSaturation: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, brightness: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(&hue, saturation: nil, brightness: &brightness, alpha: &alpha)
        return UIColor(hue: hue, saturation: newSaturation, brightness: brightness, alpha: alpha)
    }
    func colorWithBrightness(newBrightness: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, saturation: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(&hue, saturation: &saturation, brightness: nil, alpha: &alpha)
        return UIColor(hue: hue, saturation: saturation, brightness: newBrightness, alpha: alpha)
    }
    func colorWithAlpha(newAlpha: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, saturation: CGFloat = 1.0, brightness: CGFloat = 1.0
        self.getHue(&hue, saturation: &saturation, brightness: &brightness, alpha: nil)
        return UIColor(hue: hue, saturation: saturation, brightness: brightness, alpha: newAlpha)
    }
    func colorWithHighlight(highlight: CGFloat) -> UIColor {
        var red: CGFloat = 1.0, green: CGFloat = 1.0, blue: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        return UIColor(red: red * (1-highlight) + highlight, green: green * (1-highlight) + highlight, blue: blue * (1-highlight) + highlight, alpha: alpha * (1-highlight) + highlight)
    }
    func colorWithShadow(shadow: CGFloat) -> UIColor {
        var red: CGFloat = 1.0, green: CGFloat = 1.0, blue: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        return UIColor(red: red * (1-shadow), green: green * (1-shadow), blue: blue * (1-shadow), alpha: alpha * (1-shadow) + shadow)
    }
}



extension NSShadow {
    convenience init(color: AnyObject!, offset: CGSize, blurRadius: CGFloat) {
        self.init()
        self.shadowColor = color
        self.shadowOffset = offset
        self.shadowBlurRadius = blurRadius
    }
}
